#!/bin/bash

for file in *
do
    if [[ $file == *.mp4 ]] || [[ $file == *.mkv ]] || [[ $file == *.avi ]]
    then
        echo -n "Encoding $file "
        filename=$(basename "$file")
        filename="${filename%.*}"
        subs="$filename.srt"
        CMD="HandBrakeCLI -i \"$file\" -o /home/sk/\"$filename\"-sk.mp4 --preset=AppleTV 3"
        if [ -e "$subs" ]
        then
	    CODESET_TEST=`file "$subs" | cut -f2 -d':' | cut -f2 -d' ' | tr -d ' '`
	    if [ "$CODESET_TEST" == "ISO-8859" ]; then
		    CODESET="ISO_8859-7"
	    elif [ "$CODESET_TEST" == "ASCII" ]; then
		    CODESET="ISO_8859-7"
	    elif [ "$CODESET_TEST" == "Non-ISO" ]; then
		    CODESET="ISO_8859-7"
	    elif [ "$CODESET_TEST" == "UTF-8" ]; then
		    CODESET="UTF-8"
	    elif [ "$CODESET_TEST" == "Little-endian" ]; then
		    CODESET="UTF-8"
	    fi
	    CMD="$CMD --srt-file \"$subs\" --srt-codeset $CODESET --srt-burn"
	    echo -n "with subs ($CODESET).. "
        else
            echo -n "without subs.."
        fi

        eval "$CMD > /dev/null 2>&1"

        echo "done"
    fi
done

