xset r rate 250 80
setxkbmap -option grp:win_space_toggle us,el
xrdb -merge ~/.Xresources
setxkbmap -option caps:escape
feh --bg-scale ~/dotfiles/bg.jpg
xrandr --output VGA-1 --primary
cat $HOME/.config/i3/config.base $HOME/.config/i3/config.local > $HOME/.config/i3/config
exec i3
