xset r rate 250 80
setxkbmap -option grp:win_space_toggle us,el
xrdb -merge ~/.Xresources
setxkbmap -option caps:escape
feh --bg-scale ~/dotfiles/bg.jpg
xrandr --output VGA-1 --primary
exec i3
#exec mate-session
#exec gnome-session
#exec startfluxbox
