
section: screens
	# three computers that are logically named:  desktop1, desktop2, and laptop
	bsd:
	kali:
end

section: links
	# larry is to the right of moe and curly is above moe
	kali:
		right = bsd

	bsd:
		right = kali
end
