
section: screens
	# three computers that are logically named:  desktop1, desktop2, and laptop
	bsd:
	kali:
	macbook:
end

section: links
	kali:
		right = bsd
        left = macbook

	bsd:
		left = kali

    macbook:
        right = kali
end
