xset r rate 250 80
setxkbmap -option grp:win_space_toggle us,el
xrdb -merge ~/.Xresources
setxkbmap -option caps:escape
xrandr --output DP-0 --primary
xrandr --output DP-2 --left-of DP-0
feh --bg-scale ~/dotfiles/bg.jpg
cat $HOME/.config/i3/config.base $HOME/.config/i3/config.local > $HOME/.config/i3/config
dbus-launch --exit-with-session i3
