xset r rate 250 80
#setxkbmap -option grp:alt_space_toggle us,el
setxkbmap -option grp:win_space_toggle us,el
setxkbmap -option caps:escape
#feh --bg-scale --no-xinerama ~/dotfiles/freebsd/bg.jpg
feh --bg-scale ~/dotfiles/freebsd/bg.jpg
xrandr --output DP-2 --primary
xrandr --output DP-4 --right-of DP-2
xrandr --output HDMI-0 --left-of DP-2
xmodmap ~/.Xmodmap
xrdb ~/.Xresources
/usr/local/bin/i3
