xset r rate 250 80
setxkbmap -option grp:win_space_toggle us,el
setxkbmap -option caps:escape
# feh --bg-scale --no-xinerama ~/dotfiles/WallpaperFusion-mindwave-7680x1080.jpg
# xrandr --output DP-2 --primary
# xrandr --output DP-4 --right-of DP-2
# xrandr --output HDMI-0 --left-of DP-2
xrdb ~/.Xresources
/usr/local/bin/i3
