xset r rate 250 80
setxkbmap -option grp:win_space_toggle us,el
xrdb -merge ~/.Xresources
setxkbmap -option caps:escape
#xrandr --setprovideroutputsource modsetting NVIDIA-0
xrandr --auto
# xrandr --dpi 92
# xrandr --output DP-1 --above eDP-1
feh --bg-scale ~/dotfiles/bg.jpg
#xinput set-prop 11 302 1
cat $HOME/.config/i3/config.base $HOME/.config/i3/config.local > $HOME/.config/i3/config
dbus-launch --exit-with-session i3
