hostname="bsd"
ifconfig_re0="DHCP"
sshd_enable="YES"
ntpd_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
dbus_enable="YES"
hald_enable="YES"
linux_enable="YES"
kld_list="nvidia-modeset vboxnetflt"
vboxnet_enable="YES"
vboxnetflt_enable="YES"
plexmediaserver_enable="YES"
