xset r rate 250 80
setxkbmap -option grp:win_space_toggle us,el
xrdb -merge ~/.Xresources
setxkbmap -option caps:escape
feh --bg-scale ~/dotfiles/bg.jpg
xrandr --output eDP-1-1 --auto
xrandr --output HDMI-0 --left-of eDP-1-1
xrandr --output DP-0 --left-of HDMI-0
xrandr --output DP-2 --left-of DP-0
cat $HOME/.config/i3/config.base $HOME/.config/i3/config.local > $HOME/.config/i3/config
exec i3
